@startuml
skinparam card {
    BackgroundColor 0
    BorderThickness 0.5
    RoundCorner 100
    FontSize 20
}

skinparam legend {
    FontStyle bold
}

skinparam footer {
    FontSize 13
}

card "&" as q1
card "⊸" as q2
card "+" as q3
card "×" as q4
card 1 as q5

q1 -d-> q2: enqueue
q1 -d-> q3: dequeue

q2 -u-> q1: A

q3 -d-> q4: some
q3 -d-> q5: none

q4 -u-> q1: A

legend queue<sub>A</sub>
footer server
@enduml