@startuml
!include ../styles.puml!transaction

card Alice {
    label nothing
}

card Bob {
    circle "[[/work/transaction-types/queue-example/diagrams/queue-client/{queue} queue]]" as queue1 <<client>>
}

card Carol {
    circle "[[/work/transaction-types/queue-example/diagrams/queue-server/{queue} queue]]" as queue2 <<server>>
}

queue1 -- queue2
@enduml