@startuml
!include ../../../../styles.puml!session

card "⊸" as s1
card 1 as s2

s1 -> s2: [[/work/transaction-types/queue-example/diagrams/queue-client/{queue} queue]]

legend capability
caption receive
@enduml