@startuml(id=session)
skinparam card {
    BorderThickness 0.5
    BackgroundColor 0
    RoundCorner 50
    FontSize 20
}

skinparam legend {
    FontStyle bold
}

skinparam caption {
    FontStyle italic
}
@enduml

@startuml(id=transaction)
left to right direction

skinparam card {
    BorderThickness 0.5
    BackgroundColor 0
}

skinparam cloud {
    BorderThickness 0.5
    BackgroundColor 0
}

skinparam label {
    FontSize 0
}
@enduml

@startuml(id=interaction)
left to right direction

skinparam nodesep 1
skinparam ranksep 20

skinparam card {
    BorderThickness 0.5
    BackgroundColor 0
}

skinparam cloud {
    BorderThickness 0.5
    BackgroundColor 0
}

skinparam interface {
    FontSize 0
}

skinparam label {
    FontSize 18
}

skinparam note {
  TextAlignment center
}

skinparam legend {
  BackgroundColor transparent
}

hide <<hidden>>
hide <<hidden>> stereotype
@enduml